POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "This blog post is something I really like",
  "author": "John Doe",
  "url": "https://example.com/this-blog-post-is-something-i-really-like",
  "likes": 55
}